/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <iostream>
using namespace std;

int main() {
	int previous = 1;
	int digit = 2;
	int nextdigit = 0;
	int sum = 2;
	//sum is 3 because program starts counting Fibbonacci numbers from 3.
	while (nextdigit < 4000000){
		nextdigit = previous + digit;
		cout << nextdigit << endl;
		if (nextdigit % 2 == 0) sum += nextdigit;
		previous = digit;
		digit = nextdigit;

	}
	cout << "The sum is " << sum;
}
